const DB_STORE_ACTION_TYPES = {
  FETCH_DB_STORE_START: 'db_store/FETCH_DB_STORE_START',
  FETCH_DB_STORE_SUCCESS: 'db_store/FETCH_DB_STORE_SUCCESS',
  FETCH_DB_STORE_FAILED: 'db_store/FETCH_DB_STORE_FAILED',
};

export default DB_STORE_ACTION_TYPES;