const EVENTS_ACTION_TYPES = {
  FETCH_EVENTS_START: 'events/FETCH_EVENTS_START',
  FETCH_EVENTS_SUCCESS: 'events/FETCH_EVENTS_SUCCESS',
  FETCH_EVENTS_FAILED: 'events/FETCH_EVENTS_FAILED',
};

export default EVENTS_ACTION_TYPES;