const SIGNUPS_ACTION_TYPES = {
  FETCH_SIGNUPS_START: 'signups/FETCH_SIGNUPS_START',
  FETCH_SIGNUPS_SUCCESS: 'signups/FETCH_SIGNUPS_SUCCESS',
  FETCH_SIGNUPS_FAILED: 'signups/FETCH_SIGNUPS_FAILED',
};

export default SIGNUPS_ACTION_TYPES;