const MEETINGS_ACTION_TYPES = {
  FETCH_MEETINGS_START: 'meetings/FETCH_MEETINGS_START',
  FETCH_MEETINGS_SUCCESS: 'meetings/FETCH_MEETINGS_SUCCESS',
  FETCH_MEETINGS_FAILED: 'meetings/FETCH_MEETINGS_FAILED',
};

export default MEETINGS_ACTION_TYPES;