const USERS_LIST_ACTION_TYPES = {
  FETCH_USERS_LIST_START: 'users_list/FETCH_USERS_LIST_START',
  FETCH_USERS_LIST_SUCCESS: 'users_list/FETCH_USERS_LIST_SUCCESS',
  FETCH_USERS_LIST_FAILED: 'users_list/FETCH_USERS_LIST_FAILED',
};

export default USERS_LIST_ACTION_TYPES;