const PAID_MEMBERS_ACTION_TYPES = {
  FETCH_PAID_MEMBERS_START: 'paid_members/FETCH_PAID_MEMBERS_START',
  FETCH_PAID_MEMBERS_SUCCESS: 'paid_members/FETCH_PAID_MEMBERS_SUCCESS',
  FETCH_PAID_MEMBERS_FAILED: 'paid_members/FETCH_PAID_MEMBERS_FAILED',
};

export default PAID_MEMBERS_ACTION_TYPES;